### PR TITLE
Henk signed CLA

### PR DESCRIPTION
**Pull request by henkvancann**

### CODE REVIEW

**Comment by wolfmcnally** [comment]
Some of these additions may or may not be relevant to our needs for Gordian Guardian documentation. I've referred this to Shannon for review.

**Comment by henkvancann** [comment]
No prob, if you don't want a Q&A in this form, just forget about it. 
If the rhetorical questions aren't good enough, then I invite everyone to improve them. Dito the answers.

**Comment by shannona** [comment]
I didn't read the docs line by line, but:

1) The glossary looks useful. I can see including it as an appendix in a full manual/our doc section. We'd at that point want to fully edit it, and make sure we're happy with all the terms.

2) The FAQ is a work-in-progress. I think Henk is asking good questions, and the answers will be useful. There might need to be some differentiation into technical and non-technical FAQs, not sure yet. I'm agnostic on incorporating the FAQ now and continuing to update it or waiting until it's more complete. Nothing wrong with having a work-in-progress in the repo, IMO, it just shouldn't be linked until it's more complete. I should edit that too when Henk tells me it's ready to go.

**Comment by shannona** [comment]
One other comment on the glossary: we should cut it back to only include the terms relevant to GG. We don't want to mislead people into thinking DIDs or such are integrated into the app right. And, shorter will help people get to the core information. So I'd suggest cutting it back before integration.

So, in short: let's cut the Glossary to what's relavent to GG now (maybe there will be stuff to add back in later), and we could either incorporate the FAQ now or wait until it's more filled out.

**Review by shannona — CHANGES_REQUESTED** [review]
See comments on PR. Suggest cutting down glossary and filling in FAQ now or later.

**Comment by henkvancann** [comment]
> See comments on PR. Suggest cutting down glossary and filling in FAQ now or later.

Yes, I've put a day in my agenda to give this full attention: Wednesday April 28th. First I'd like to study the ins and outs, run a Testflight and then amend / add to the Q&A.

**Pull request closed without merging**
